export const ACTION_INCREMENT = 'ACTION_INCREMENT';
export const ACTION_DECREMENT = 'ACTION_DECREMENT';
export const ACTION_COUNTER_RESET = 'ACTION_COUNTER_RESET';

export const ACTION_ADD_TODO = 'ACTION_ADD_TODO';
export const ACTION_UPDATE_TODO = 'ACTION_UPDATE_TODO';
export const ACTION_DELETE_TODO = 'ACTION_DELETE_TODO';
export const ACTION_RESET_TODO = 'ACTION_RESET_TODO';
